[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NADY"
authors = [{name = "Marko", email = "segprt@gmail.com"}]
dynamic = ["version", "description"]
